name: CI/CD

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Instalar HTMLHint
        run: npm install -g htmlhint

      - name: Executar HTMLHint
        run: htmlhint "**/*.html"

      - name: Instalar Stylelint
        run: |
          npm install -g stylelint
          npm install -g stylelint-config-standard

      - name: Criar configuração Stylelint
        run: |
          echo '{
            "extends": "stylelint-config-standard"
          }' > .stylelintrc.json

      - name: Executar Stylelint
        run: stylelint "**/*.css"

  build:
    name: Build
    needs: lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Verificar arquivos obrigatórios
        run: |
          test -f index.html
          test -f styles/style.css

      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload do site
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

  deploy:
    name: Deploy
    if: github.ref == 'refs/heads/main'

    needs: build

    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Publicar no GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4